// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP9YVo6XkwIPdUMO3uVnoI4WrcUKuFZOc',
    appId: '1:915426134307:web:98a820bb51b95fd2f6e496',
    messagingSenderId: '915426134307',
    projectId: 'money-maker-24c17',
    authDomain: 'money-maker-24c17.firebaseapp.com',
    storageBucket: 'money-maker-24c17.firebasestorage.app',
    measurementId: 'G-SV6MDG9256',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDuSWjdZgXxuu7ywDlhCDAbQYeYqFqg-A',
    appId: '1:915426134307:android:1fef627200077729f6e496',
    messagingSenderId: '915426134307',
    projectId: 'money-maker-24c17',
    storageBucket: 'money-maker-24c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7eRf6ypS_iSbqOLdynNdG6HqtomqYBo',
    appId: '1:915426134307:ios:04f58e7837060bc7f6e496',
    messagingSenderId: '915426134307',
    projectId: 'money-maker-24c17',
    storageBucket: 'money-maker-24c17.firebasestorage.app',
    iosBundleId: 'com.example.moneyMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx7eRf6ypS_iSbqOLdynNdG6HqtomqYBo',
    appId: '1:915426134307:ios:04f58e7837060bc7f6e496',
    messagingSenderId: '915426134307',
    projectId: 'money-maker-24c17',
    storageBucket: 'money-maker-24c17.firebasestorage.app',
    iosBundleId: 'com.example.moneyMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP9YVo6XkwIPdUMO3uVnoI4WrcUKuFZOc',
    appId: '1:915426134307:web:0ccfb63c23adc724f6e496',
    messagingSenderId: '915426134307',
    projectId: 'money-maker-24c17',
    authDomain: 'money-maker-24c17.firebaseapp.com',
    storageBucket: 'money-maker-24c17.firebasestorage.app',
    measurementId: 'G-BHQW6XZGYV',
  );
}